export default [
  {
      id: 1,
      postedOn: '2023-10-28',
      title: 'iOS Developer',
      company: 'Apple',
      type: 'Full Time',
      experience: 'Mid Level',
      location: 'Remote',
      skills: ["SwiftUI", "UIKit", "Core Data"],
      job_link: "https://www.apple.com/careers/in/",
  },
  {
      id: 2,
      postedOn: '2023-10-24',
      title: "Frontend Developer",
      type: "Full Time",
      location: "In-office",
      experience: "Fresher",
      company: "Amazon",
      skills: ["JavaScript", "Next.js", "Tailwind CSS"],
      job_link: "https://www.amazon.jobs/en/",
  },
  {
      id: 3,
      postedOn: '2023-11-02',
      title: "Android Developer",
      type: "Part Time",
      location: "Remote",
      experience: "Senior Level",
      company: "Facebook",
      skills: ["Kotlin", "MVVM"],
      job_link: "https://facebook.com/careers",
  },
  {
      id: 4,
      postedOn: '2023-11-01',
      title: "Developer Advocate",
      type: "Contract",
      location: "Hybrid",
      experience: "Junior Level",
      company: "Netflix",
      skills: ["Web3", "Content Creation", "Community"],
      job_link: "https://jobs.netflix.com/",
  },
  {
      id: 5,
      postedOn: '2023-11-05',
      title: "Backend Developer",
      type: "Full Time",
      location: "In-office",
      experience: "Mid Level",
      company: "Google",
      skills: ["Node.js", "Express", "MongoDB"],
      job_link: "https://careers.google.com/",
  },
  {
      id: 6,
      postedOn: '2023-11-07',
      title: "Data Scientist",
      type: "Full Time",
      location: "Remote",
      experience: "Senior Level",
      company: "Tesla",
      skills: ["Python", "Machine Learning", "TensorFlow"],
      job_link: "https://www.tesla.com/careers",
  },
  {
      id: 7,
      postedOn: '2023-11-10',
      title: "Cybersecurity Engineer",
      type: "Full Time",
      location: "Hybrid",
      experience: "Junior Level",
      company: "Microsoft",
      skills: ["Network Security", "Ethical Hacking", "Cloud Security"],
      job_link: "https://careers.microsoft.com/",
  },
  {
      id: 8,
      postedOn: '2023-11-12',
      title: "Game Developer",
      type: "Contract",
      location: "Remote",
      experience: "Fresher",
      company: "Epic Games",
      skills: ["C++", "Unreal Engine", "Game Physics"],
      job_link: "https://www.epicgames.com/careers",
  },
  {
      id: 9,
      postedOn: '2023-11-15',
      title: "AI Research Engineer",
      type: "Full Time",
      location: "In-office",
      experience: "Mid Level",
      company: "OpenAI",
      skills: ["Deep Learning", "Transformers", "NLP"],
      job_link: "https://openai.com/careers",
  },
];
